### ISSUE TITLE
Transactions for wallets aren't updated since 2022-01-07 18:25 UTC

### ISSUE THREAD

**Issue by Alex0007** [stellar-expert/stellar-expert-explorer#582] opened 2022-01-08 12:08 UTC

**Comment by remarkablemayonaise** [comment] 2022-01-08 15:35
Well observed! I always forget how delicate Stellar is! In November 2021 I has had a similar issue with the (not so reassuring reply):

"One of our Stellar Core nodes fell out of consensus, which led to the disruption of our historical data ingestion process... Sorry for the inconvenience."

It always happens when I'm trying to mint coins or something where stellar.expert is a much better ready reckoner than end point scraping!

**Comment by Alex0007** [comment] 2022-01-08 18:10
Now transactions are stopped at 2022-01-08 13:41 UTC

**Comment by orbitlens** [comment] 2022-01-08 19:13
Ledger ingestion process has been restored. This issue is fixed now. 
The root of the problem is pretty much the same. When our nodes loose track of consensus, the process is disrupted.

We are actively working on measures to reduce the downtime in the future and make our nodes more resilient.

**Closed by orbitlens** 2022-01-08 19:13 UTC

**Comment by Alex0007** [comment] 2022-01-26 02:43
@orbitlens seems like it's happened again

**Comment by Alex0007** [comment] 2022-02-14 21:55
@orbitlens not updating again

**Comment by Alex0007** [comment] 2022-02-22 17:22
@orbitlens not updating

**Comment by Alex0007** [comment] 2022-03-07 02:55
@orbitlens not updating 2 days

**Comment by orbitlens** [comment] 2022-03-07 04:12
> @orbitlens not updating 2 days

@Alex0007 Still working on a fix for this. I'll provide the ETA in 5-6 hours.

**Comment by orbitlens** [comment] 2022-03-07 09:17
> @Alex0007 Still working on a fix for this. I'll provide the ETA in 5-6 hours.

Fix deployed. Ingestion engine should catch up with recent entries in a few hours.

**Comment by Alex0007** [comment] 2022-03-13 06:04
@orbitlens not updating

**Comment by orbitlens** [comment] 2022-03-13 06:11
> @orbitlens not updating

I'm upgrading our Stellar Core nodes v18.1.0->v18.4.0 right now. The ingestion process will restart in about 50 minutes.  
Probably, we should think about a way to communicate scheduled maintenance windows. Sorry for the inconvenience.

**Comment by Alex0007** [comment] 2022-03-17 06:18
@orbitlens not updating more than 24 hours

**Comment by Alex0007** [comment] 2022-05-11 20:05
@orbitlens stuck again

**Comment by Alex0007** [comment] 2022-05-12 10:24
@orbitlens 
unsynced again

**Comment by orbitlens** [comment] 2022-05-12 11:05
@Alex0007 Sorry, the synchronization process has been unstable lately. We often experience ~1h hiccups due to huge on-chain activity + extensive API usage from third-parties, which leads to the dramatic database performance disruption. We try to keep up with the avalanche-like network growing, but the improvements are pretty slow - any major infrastructure/database/ingestion improvement takes about 3 weeks to apply (that's the time required to re-ingest entire 6 year blockchain history).
