### ISSUE TITLE
StellarExpert Testnet Ledger not updated to current ledger

### ISSUE THREAD

**Issue by ifgrcm** [stellar-expert/stellar-expert-explorer#527] opened 2021-09-01 15:51 UTC
It appears the StellarExpert testnet is not updated to current ledger.  See account below as an example:

https://stellar.expert/explorer/testnet/account/GDFJDCFTCPYP4CQAQFWJ5RKKHQA6OSWLC5F63V2XCYCBUODLFKN3OPFL
http://testnet.stellarchain.io/address/GDFJDCFTCPYP4CQAQFWJ5RKKHQA6OSWLC5F63V2XCYCBUODLFKN3OPFL

**Comment by BlockShangerous** [comment] 2021-09-03 00:09
Same issue. Seems like it stopped around 8-23
None of my new accounts show up
https://stellar.expert/explorer/testnet/account/GCQJZ77TIW2ANJCFGLN4CLXCBL2HXSY5KT7LNMRNK7G4JS7OMTB5KMQZ
https://testnet.steexp.com/account/GCQJZ77TIW2ANJCFGLN4CLXCBL2HXSY5KT7LNMRNK7G4JS7OMTB5KMQZ#balances
but they show up on other explorers.
SOURCE also asked about this in the discord https://discord.com/channels/761985725453303838/761985800132493354/883015916621799424

**Comment by orbitlens** [comment] 2021-09-04 07:44
We had an issue with our testnet Stellar Core node. We tried to fix the corrupted database, but in the end decided to recreate the node. The ingestion problem is fixed now.
Sorry for the delay.

**Closed by orbitlens** 2021-09-04 07:44 UTC

**Comment by orbitlens** [comment] 2021-12-15 05:02
The issue was caused by the claimable balances ingestion error. Fixed.
Please note, testnet will be [recreated](https://status.stellar.org/incidents/11jxl3t4qs2r) tomorrow, so all your test accounts will disappear.

**Comment by ckz8780** [comment] 2021-12-15 17:16
Thank you for the reply! Looks like it's all working again. Cheers
